[package]
name = "heapsize_derive"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proc-macro2 = "1.0.64"
quote = "1.0"
syn = "1.0"

[lib]
proc-macro = true # 需要标明crate是生成宏类型

