[workspace]
resolver = "2"

members = [
    "examples/study",
    "pkg/util",
    "pkg/core",
    "pkg/dns/name",
    "pkg/dns",
    "cmd"
]

# Debug symbols end up chewing up several GB of disk space, so better to just
# disable them.
[profile.dev]
debug = false

[profile.test]
debug = false

[profile.release]
lto = true