[package]
name = "proxies-dns-name"
version = "0.1.0"
authors = ["Proxies Developers <quwenbin>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1"
untrusted = "0.7"
